### ISSUE TITLE
ellipse.default(): center has no effect

### ISSUE THREAD

**Issue by dwoll** [dmurdoch/ellipse#1]
Many thanks for developing `ellipse` and for putting the source on GitHub! I'm wondering if the addition of argument `center` is as intended. `centre` is used on line 27/28 https://github.com/dmurdoch/ellipse/blob/e41ef76bea077a97a12d5ff821e8c426399824e7/R/ellipse.default.R#L27

However, there is no previous assignment `centre <- center` conditional on `center` being supplied but not `centre`. Consider

```
> e1 <- ellipse:::ellipse.default(0.8, center=c(1, 2))
> e2 <- ellipse:::ellipse.default(0.8, center=c(0, 0))
> all.equal(e1, e2)
[1] TRUE
```

Using `centre` instead really gives different ellipses.
Note there is a typo in the warning on line 7 (one should be `center`) https://github.com/dmurdoch/ellipse/blob/e41ef76bea077a97a12d5ff821e8c426399824e7/R/ellipse.default.R#L7

Thanks in advance!

**Comment by dmurdoch** [comment]
Yes, you're right.  I'll fix it.

**Comment by dmurdoch** [comment]
Now fixed.  I'll wait a few days to see if anything else turns up before sending this to CRAN.

**Comment by dwoll** [comment]
Thank you very much!

**Comment by dmurdoch** [comment]
Just accepted by CRAN.  Thanks for the report!
